---
- hosts: all

  tasks:

    - name: Reset interfaces
      ansible.netcommon.cli_command:
        command: "{{ item }}"
        sendonly: yes
      loop:
        - configure
        - default interface range ethernet 1/1/1-1/1/54
        - 'yes'
        - exit

    - name: Delete VLANs
      dellemc.os10.os10_config:
        lines: 
          - "no interface {{ item }}"
      loop: "{{ os10_interface.keys() }}"
